version: '3.8'
name: boilerplates
services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: nuxt3_auth
    command: yarn dev
    volumes:
    - ./:/app:rw
    - /app/node_modules/
    ports:
      - "3000:3000"