# use node 18 alpine image as build image
FROM node:18-alpine as base

# update and install the latest dependencies for the alpine version
RUN apk update && apk upgrade

# create work directory in app folder
WORKDIR /app

# install required packages for node image
RUN apk --no-cache add openssh g++ make python3 git

FROM base as builder

# copy over package.json files
COPY --link package* /app
COPY --link yarn* /app

# install all depencies
RUN yarn install && yarn cache clean --force

# copy over all files to the work directory
ADD . /app

# build the project
RUN yarn build

# start final image
FROM base

# update and install the latest dependencies for the alpine version
RUN apk update && apk upgrade

WORKDIR /app

# copy over build files from builder step
COPY --from=builder /app  /app

# expose the host and port 3000 to the server
ENV HOST=0.0.0.0 PORT=24678 NODE_ENV=development chokidar_usepolling=true
ENV PATH=./node_modules/.bin/:$PATH

EXPOSE 24678

CMD ["yarn", "dev"]