version: '3.8'
name: boilerplates
services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nuxt3_auth
    environment:
      - chokidar_usepolling=true
    command: yarn dev
    volumes:
    - ./:/app:rw
    - /app/node_modules/
    ports:
      - "24678:24678"
    networks:
      - boilerplates

networks:
  boilerplates:
    driver: bridge